from typing import Any

def create_sub_interpreter() -> Any: ...
def run_code(interpreter_state: Any, path_to_compiled_code: str) -> None: ...
def close_sub_interpreter(interpreter_state: Any) -> None: ...
