#!/bin/bash

# Function to check if a command exists
command_exists () {
    type "$1" &> /dev/null ;
}

# make sure python version is 3.12 or higher

# Python execution logic
if command_exists python ; then
    PYTHON_CMD=python
elif command_exists python3 ; then
    PYTHON_CMD=python3
else
    echo "Python is not installed or not found in PATH"
    exit 1
fi

echo "Using Python command: $PYTHON_CMD"

version = $("$PYTHON_CMD --version")

if [[ "$version" < "3.12" ]]; then
    echo "Python version is too low. Please install Python 3.12 or higher."
    exit 1
fi

# Creating a virtual environment
$PYTHON_CMD -m venv .venv

# Activating the virtual environment and installing requirements
# Different commands for Windows and Unix-like systems
if [[ "$OSTYPE" == "msys"* ]] || [[ "$OSTYPE" == "win32"* ]]; then
    .venv\Scripts\activate
else
    source .venv/bin/activate
fi

pip install -r requirements.txt

echo "Setup completed successfully."