# this is the build file for project helix-lang
# it is autogenerated by the xmake build system.
# do not edit by hand.

ifneq ($(VERBOSE),1)
VV=@
endif

CXX=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
SC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend
AS=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
MXX=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
MM=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
RC=/Users/dhruvan/.cargo/bin/rustc
CU=/opt/homebrew/opt/llvm/bin/clang

AR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar
RCAR=/Users/dhruvan/.cargo/bin/rustc
LD=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
RCLD=/Users/dhruvan/.cargo/bin/rustc
SCLD=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc
SH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
RCSH=/Users/dhruvan/.cargo/bin/rustc
SCSH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc

helix_LD=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
helix_CXX=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
helix_CXX=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang

helix_CXXFLAGS=-Qunused-arguments -target arm64-apple-macos14.5 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -fvisibility=hidden -fvisibility-inlines-hidden -Wall -O3 -std=c++2b -DNDEBUG
helix_CXXFLAGS=-Qunused-arguments -target arm64-apple-macos14.5 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -fvisibility=hidden -fvisibility-inlines-hidden -Wall -O3 -std=c++2b -DNDEBUG
helix_LDFLAGS=-target arm64-apple-macos14.5 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -lz -Wl,-x -Wl,-dead_strip

default:  helix

all:  helix

.PHONY: default all  helix

helix: build/macosx/arm64/release/helix
build/macosx/arm64/release/helix: build/.objs/helix/macosx/arm64/release/source/main.cc.o build/.objs/helix/macosx/arm64/release/source/token/source/lexer.cc.o build/.objs/helix/macosx/arm64/release/source/token/source/token.cc.o build/.objs/helix/macosx/arm64/release/source/include/error/error.cc.o build/.objs/helix/macosx/arm64/release/source/cli/cli.cc.o build/.objs/helix/macosx/arm64/release/source/parser/ast/classes/nodes.cc.o build/.objs/helix/macosx/arm64/release/source/parser/ast/classes/ast.cc.o
	@echo linking.release helix
	@mkdir -p build/macosx/arm64/release
	$(VV)$(helix_LD) -o build/macosx/arm64/release/helix build/.objs/helix/macosx/arm64/release/source/main.cc.o build/.objs/helix/macosx/arm64/release/source/token/source/lexer.cc.o build/.objs/helix/macosx/arm64/release/source/token/source/token.cc.o build/.objs/helix/macosx/arm64/release/source/include/error/error.cc.o build/.objs/helix/macosx/arm64/release/source/cli/cli.cc.o build/.objs/helix/macosx/arm64/release/source/parser/ast/classes/nodes.cc.o build/.objs/helix/macosx/arm64/release/source/parser/ast/classes/ast.cc.o $(helix_LDFLAGS)

build/.objs/helix/macosx/arm64/release/source/main.cc.o: source/main.cc
	@echo compiling.release source/main.cc
	@mkdir -p build/.objs/helix/macosx/arm64/release/source
	$(VV)$(helix_CXX) -c $(helix_CXXFLAGS) -o build/.objs/helix/macosx/arm64/release/source/main.cc.o source/main.cc

build/.objs/helix/macosx/arm64/release/source/token/source/lexer.cc.o: source/token/source/lexer.cc
	@echo compiling.release source/token/source/lexer.cc
	@mkdir -p build/.objs/helix/macosx/arm64/release/source/token/source
	$(VV)$(helix_CXX) -c $(helix_CXXFLAGS) -o build/.objs/helix/macosx/arm64/release/source/token/source/lexer.cc.o source/token/source/lexer.cc

build/.objs/helix/macosx/arm64/release/source/token/source/token.cc.o: source/token/source/token.cc
	@echo compiling.release source/token/source/token.cc
	@mkdir -p build/.objs/helix/macosx/arm64/release/source/token/source
	$(VV)$(helix_CXX) -c $(helix_CXXFLAGS) -o build/.objs/helix/macosx/arm64/release/source/token/source/token.cc.o source/token/source/token.cc

build/.objs/helix/macosx/arm64/release/source/include/error/error.cc.o: source/include/error/error.cc
	@echo compiling.release source/include/error/error.cc
	@mkdir -p build/.objs/helix/macosx/arm64/release/source/include/error
	$(VV)$(helix_CXX) -c $(helix_CXXFLAGS) -o build/.objs/helix/macosx/arm64/release/source/include/error/error.cc.o source/include/error/error.cc

build/.objs/helix/macosx/arm64/release/source/cli/cli.cc.o: source/cli/cli.cc
	@echo compiling.release source/cli/cli.cc
	@mkdir -p build/.objs/helix/macosx/arm64/release/source/cli
	$(VV)$(helix_CXX) -c $(helix_CXXFLAGS) -o build/.objs/helix/macosx/arm64/release/source/cli/cli.cc.o source/cli/cli.cc

build/.objs/helix/macosx/arm64/release/source/parser/ast/classes/nodes.cc.o: source/parser/ast/classes/nodes.cc
	@echo compiling.release source/parser/ast/classes/nodes.cc
	@mkdir -p build/.objs/helix/macosx/arm64/release/source/parser/ast/classes
	$(VV)$(helix_CXX) -c $(helix_CXXFLAGS) -o build/.objs/helix/macosx/arm64/release/source/parser/ast/classes/nodes.cc.o source/parser/ast/classes/nodes.cc

build/.objs/helix/macosx/arm64/release/source/parser/ast/classes/ast.cc.o: source/parser/ast/classes/ast.cc
	@echo compiling.release source/parser/ast/classes/ast.cc
	@mkdir -p build/.objs/helix/macosx/arm64/release/source/parser/ast/classes
	$(VV)$(helix_CXX) -c $(helix_CXXFLAGS) -o build/.objs/helix/macosx/arm64/release/source/parser/ast/classes/ast.cc.o source/parser/ast/classes/ast.cc

clean:  clean_helix

clean_helix: 
	@rm -rf build/macosx/arm64/release/helix
	@rm -rf build/macosx/arm64/release/helix.dSYM
	@rm -rf build/.objs/helix/macosx/arm64/release/source/main.cc.o
	@rm -rf build/.objs/helix/macosx/arm64/release/source/token/source/lexer.cc.o
	@rm -rf build/.objs/helix/macosx/arm64/release/source/token/source/token.cc.o
	@rm -rf build/.objs/helix/macosx/arm64/release/source/include/error/error.cc.o
	@rm -rf build/.objs/helix/macosx/arm64/release/source/cli/cli.cc.o
	@rm -rf build/.objs/helix/macosx/arm64/release/source/parser/ast/classes/nodes.cc.o
	@rm -rf build/.objs/helix/macosx/arm64/release/source/parser/ast/classes/ast.cc.o

